#配置执行的测试用例
'TeacheManage':
  'TeacheManage': true
  'test1_add_teacher': true
  'test2_del_teacher': false
'StudentManage':
  'StudentManage': true
  'test1_add_student': true
  'test2_del_student': false
